version: '3'
services:
  julia:
    image: jupyter/datascience-notebook
    volumes:
      - ./:/home/jovyan
    ports:
      - "8888:8888"
    #command: jupyter-notebook --ip=0.0.0.0 --allow-root --NotebookApp.token='' --port=8888
    command: jupyter lab --ip=0.0.0.0 --allow-root --NotebookApp.token='' --port=8888
